version: 2.1

workflows:
  version: 2
  ci_flow:
    jobs:
      - build
      - test
  cicd_flow:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: release

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: mvn clean compile
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: mvn test
  deploy:
    docker:
      - image: circleci/aws-cli
    steps:
      - run:
          name: Deploy to AWS
          command: |
            aws s3 sync target s3://sctpmod4bucket --delete
